# Server Configuration
server.port=8080

# Database Configuration (Kh?p v?i DataGrip/Docker)
spring.datasource.url=jdbc:mysql://localhost:3306/echommo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.open-in-view=false

# JWT Secret (Chu?i bí m?t ?? mã hóa token - C?c quan tr?ng)
app.jwtSecret=EchoMMOSecretKeyForLuNuTrungTinhProject2025CreateByGemini
app.jwtExpirationInMs=86400000

# CORS (Cho phép VueJS g?i vào)
app.cors.allowedOrigins=http://localhost:5173

# MAIL CONFIG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=echommofpoly@gmail.com
spring.mail.password=uwefajgdwsqjbxql
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true